### ISSUE TITLE
Cannot find module './history'.

### ISSUE THREAD

**Issue by zswang** [techird/svg-board#1]
```shell
$ npm run dev
```

```shell
ERROR in ./app/stores/createStore.ts
(5,31): error TS2307: Cannot find module './history'.
```

**Comment by techird** [comment]
It was my mistake to commit some undone work. Already fixed in the new branch [new-for-shanghai](https://github.com/techird/svg-board/tree/new-for-shanghai). The new branch is going to add some cool features which will be merged into master in the following week. You might check it out in #2 .

**Comment by techird** [comment]
Fixed
